version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: customer_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mock-server:
    build: ./mock-server
    container_name: flask_mock_server
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./mock-server:/app

  pipeline-service:
    build: ./pipeline-service
    container_name: fastapi_pipeline
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mock-server:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/customer_db
      MOCK_SERVER_URL: http://mock-server:5000
    volumes:
      - ./pipeline-service:/app

volumes:
  postgres_data: